# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/scaling-computing-machine',
                'doc_host': 'https://davidrkearney.github.io',
                'git_url': 'https://github.com/davidrkearney/scaling-computing-machine',
                'lib_path': 'scaling_computing_machine'},
  'syms': { 'scaling_computing_machine.core': { 'scaling_computing_machine.core.foo': ( 'core.html#foo',
                                                                                        'scaling_computing_machine/core.py')}}}